In [2]:
import pandas as pd
import numpy as np

In [ ]:
# 2장 / 2.1 실수자료로의 전환(vectorization)

# 1.실수자료로의 전환(vectorization)

In [ ]:
## 범주형 자료의 수량화

In [2]:
x = [{'city':'seoul', 'temp':10.0}, {'city':'Dubai', 'temp':33.5}, {'city':'LA', 'temp':20.0}]
x

[{'city': 'seoul', 'temp': 10.0},
 {'city': 'Dubai', 'temp': 33.5},
 {'city': 'LA', 'temp': 20.0}]

In [3]:
from sklearn.feature_extraction import DictVectorizer  #딕셔너리->벡터
vec=DictVectorizer(sparse=False)  #vec으로 객체화
vec.fit_transform(x)  #x를 범주형 수량화 자료로 변환 -> one-hot 벡터

array([[ 0. ,  0. ,  1. , 10. ],
       [ 1. ,  0. ,  0. , 33.5],
       [ 0. ,  1. ,  0. , 20. ]])

In [4]:
vec1=DictVectorizer(sparse=True)  #메모리를 줄이기 위해 sparse=True
x1=vec1.fit_transform(x)
x1

<3x4 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [5]:
x2=x1.toarray()  #sparse=True를 풀고, 배열로 변경 
print(x1) ##sparse=True, sparse 행렬 (원래의 범주형 자료를 출력)
print(x2) ##sparse=False

vec1.get_feature_names() #특정변수의 이름 확인 (첫번째 열, 두번째 열, 세번째 열, 네번째 열)

  (0, 2)	1.0
  (0, 3)	10.0
  (1, 0)	1.0
  (1, 3)	33.5
  (2, 1)	1.0
  (2, 3)	20.0
[[ 0.   0.   1.  10. ]
 [ 1.   0.   0.  33.5]
 [ 0.   1.   0.  20. ]]


['city=Dubai', 'city=LA', 'city=seoul', 'temp']

In [ ]:
## text 데이터의 수량화

In [4]:
text=['떴다 떴다 비행기 날아라 날아라',
      '높이 높이 날아라 우리 비행기',
      '내가 만든 비행기 날아라 날아라',
      '멀리 멀리 날아라 우리 비행기']
text  #리스트 data

['떴다 떴다 비행기 날아라 날아라',
 '높이 높이 날아라 우리 비행기',
 '내가 만든 비행기 날아라 날아라',
 '멀리 멀리 날아라 우리 비행기']

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
vec2 = CountVectorizer() # default는 sparse=True
t = vec2.fit_transform(text).toarray() # sparse=True를 풀고 text를 수량화 배열 자료로 변환 (원래 자료로 보여주는 것)
import pandas as pd
t1 = pd.DataFrame(t, columns=vec2.get_feature_names())
t1

날아라  내가  높이  떴다  만든  멀리  비행기  우리
0    2   0   0   2   0   0    1   0
1    1   0   2   0   0   0    1   1
2    2   1   0   0   1   0    1   0
3    1   0   0   0   0   2    1   1

In [6]:
# TFIDF (Term Frequency Inverse Document Frequency) 
#  : 출현 빈도가 높은 단어 -> 상대적으로 낮은 가중치
#  : 출현 빈도가 낮은 단어 -> 상대적으로 높은 가중치

from sklearn.feature_extraction.text import TfidfVectorizer
tfid=TfidfVectorizer() #object 생성
x2=tfid.fit_transform(text).toarray() # 높은 빈도는 낮은 가중치, 낮은 빈도는 높은 가중치
x3=pd.DataFrame(x2, columns=tfid.get_feature_names())
x3

# text -> 실수로 전환 과정

날아라        내가       높이       떴다        만든       멀리       비행기        우리
0  0.450735  0.000000  0.00000  0.86374  0.000000  0.00000  0.225368  0.000000
1  0.229589  0.000000  0.87992  0.00000  0.000000  0.00000  0.229589  0.346869
2  0.569241  0.545415  0.00000  0.00000  0.545415  0.00000  0.284620  0.000000
3  0.229589  0.000000  0.00000  0.00000  0.000000  0.87992  0.229589  0.346869

In [7]:
## Polynomial 특정변수 생성

# : 특정 변수를 생성하여 비선형 -> 선형
# : 적합을 목표로 사용

In [22]:
import plotly.express as px  # plotly : 그림 그리기 위한 라이브러리
import numpy as np

X=np.array([1,2,3,4,5])
Y=np.array([5,3,1,5,8])
fig=px.line(x=X,y=Y) #선형회귀를 하기에는 부적합
fig.update_layout(width=500,height=380)
fig.show()

In [9]:
# (특정 변수 생성)

from sklearn.preprocessing import PolynomialFeatures  #사전정리
fg=PolynomialFeatures(degree=3, include_bias=True)  #degree : 3승까지 / include_bias는 절편항 여부
x1=fg.fit_transform(X[:,np.newaxis]) #3차까지 생성 / 2D tensor로 변경(sklearn)
print(x1)

[[  1.   1.   1.   1.]
 [  1.   2.   4.   8.]
 [  1.   3.   9.  27.]
 [  1.   4.  16.  64.]
 [  1.   5.  25. 125.]]


In [23]:
# Regression 그려보기 (좋은 fitting 확인)

from sklearn.linear_model import LinearRegression
import plotly.graph_objects as go
reg=LinearRegression()
reg.fit(x1, Y)
yfit=reg.predict(x1) #적합값
fig=go.Figure()
fig.add_trace(go.Scatter(x=X,y=Y,mode='lines',name='origin'))
fig.add_trace(go.Scatter(x=X,y=yfit,mode='lines+markers', name='fitted'))
fig.show()

In [11]:
## 결측 자료 대체 (inputation)
# : sklearn은 결측치가 있어서는 안된다 (계산 x)
# : 결측치를 대체 or 제거해야 함

In [12]:
# 빈도수로 대체

x_miss=np.array([[1,2,3,None],[5,np.NAN,7,8],[None,10,11,12],[13,np.nan,15,16]])
print(x_miss)

import pandas as pd
x_m=pd.DataFrame(x_miss, columns=list('abcd'))
print(x_m)

[[1 2 3 None]
 [5 nan 7 8]
 [None 10 11 12]
 [13 nan 15 16]]
      a    b   c     d
0     1    2   3  None
1     5  NaN   7     8
2  None   10  11    12
3    13  NaN  15    16


In [13]:
x_m['b']=x_m['b'].fillna(x_m['b'].mode())
print(x_m)

x_m['b']=x_m['b'].fillna(x_m['b'].mode()[0])
print(x_m)

      a     b   c     d
0     1   2.0   3  None
1     5  10.0   7     8
2  None  10.0  11    12
3    13   NaN  15    16
      a     b   c     d
0     1   2.0   3  None
1     5  10.0   7     8
2  None  10.0  11    12
3    13  10.0  15    16


In [14]:
# 평균으로 대체

from sklearn.impute import SimpleImputer
im=SimpleImputer(strategy='mean')
im.fit_transform(x_miss) #열의 평균값으로 대체

array([[ 1.        ,  2.        ,  3.        , 12.        ],
       [ 5.        ,  6.        ,  7.        ,  8.        ],
       [ 6.33333333, 10.        , 11.        , 12.        ],
       [13.        ,  6.        , 15.        , 16.        ]])